collectionspace/cspace-ui.js

- karma.conf.js
Current default is "Chrome", but on Linux Chrome is not available
by default. Allow use of KARMA_BROWSERS env var to specify which
browser(s) to use. For example:
export KARMA_BROWSERS=Firefox
export KARMA_BROWSERS=Chrome,Firefox (run both)
> For local run check env for KARMA_BROWSERS

- src/plugins/recordTypes/person/optionLists.js
**personTitles**
- Adds a number of English honorifics/titles to personTitles optionList. Base list of added terms is from a migration client's data, but all terms are generally applicable, so will be added to the base UI.
- Puts all values in alphabetical order, given current length of list making any other order seem somewhat chaotic. Megan okayed changing the order of this list. 
**genders**
Updates the genders optionList, as per https://collectionspace.atlassian.net/browse/DRYD-884
Adds [the gender terms from Art & Architecture Thesaurus](http://www.getty.edu/vow/AATHierarchy?find=&logic=AND&note=&page=1&subjectid=300411835). Also adds "transgender" and "transsexual" based on recommendations from [Billey & Drabinski (2017). Cataloging Gender and RDA Instruction …
> personTitles and genders option list updates

- src/plugins/recordTypes/insurance/fields.js
In the fields for the insurance procedure, the source for `insuranceIdemnityAuthorizer` was delimited with a `/` instead of a `,`
> Fix typo in insurance record

- src/components/record/RecordSidebar.jsx
- src/components/record/RecordTitleBar.jsx
- src/containers/input/DateTimeInputContainer.jsx
- src/containers/input/FieldTextInputContainer.jsx
- src/helpers/configContextInputs.js
- src/plugins/listTypes/audit.js
- src/plugins/recordTypes/audit/fields.js
- src/plugins/recordTypes/audit/forms/default.jsx
- src/plugins/recordTypes/audit/forms/index.js
- src/plugins/recordTypes/audit/index.js
- src/plugins/recordTypes/audit/messages.js
- src/plugins/recordTypes/audit/optionLists.js
- src/plugins/recordTypes/audit/title.js
- styles/cspace-ui/CreatePagePanel.css
- styles/cspace-ui/MiniView.css
- styles/cspace-ui/RecordBrowserNavBar.css
- styles/cspace-ui/RecordPage.css
- styles/cspace-ui/RecordSidebar.css
- styles/cspace-ui/TitleBar.css
- test/specs/containers/input/FieldTextInputContainer.spec.jsx
- test/specs/plugins/recordTypes/audit/columns.spec.js
- test/specs/plugins/recordTypes/audit/forms/default.spec.js
- test/specs/plugins/recordTypes/audit/index.spec.js
- test/specs/plugins/recordTypes/audit/optionLists.spec.js
- test/specs/plugins/recordTypes/audit/serviceConfig.spec.js
- test/specs/plugins/recordTypes/audit/title.spec.js
Resolves: https://collectionspace.atlassian.net/browse/DRYD-998
* Add a read only form for viewing Audit records
* Finish defining fields for Audit
* Start adding event types to optionLists for human readable output
* Create wrapper around TextInput for formatting Field names in audit responses
I'm not exactly sure of all the changes to the audit record between #133 and this, I know 133 only has what is necessary to get the record displayed on the sidebar.
I used the `AuditDocumentHandler` to inform parsing of the `key` field in the changed fields list, as it is used when creating the response in the services layer. There's still some work to do in order to get lists in a more human readable state and deciding what to do with other fields (e.g. `scalarValuesComputer`).
> Audit record form

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/iterationreport/fields.js
- src/plugins/recordTypes/media/fields.js
This adds dataType elements to non-string fields added to: 
- collectionobject
- media
- iterationreport
Since @mikejritter is already working in the fields.js for person for DRYD-1172, I didn't mess with those fields, to avoid conflicts
It also adds a groupName element to two structured date fields within repeating field groups that did not have that element.
> DRYD-1175 Add dataType elements to new fields 

- src/plugins/recordTypes/person/fields.js
- src/plugins/recordTypes/person/forms/default.jsx
Jira: https://collectionspace.atlassian.net/browse/DRYD-1172
* Rename supplied birthDate fields to avoid conflicts with previously defined fields
* Update messages for supplied birth date fields better indicate what they are in search
* Add groupName message for birth date structured date input
* Fix import of structured date fields for suppliedStructuredBirthDate
* Add missing dataType definitions
* Remove errant repeat declarations for suppliedStructuredBirthDate and suppliedBirthPlace
> DRYD-1172: Rename supplied birth date fields

- src/actions/record.js
- src/components/pages/RecordPage.jsx
- src/reducers/record.js
- test/specs/actions/record.spec.js
- test/specs/reducers/record.spec.js
Jira: https://collectionspace.atlassian.net/browse/DRYD-1185
* Add subrecords of primary page csid to filter
* Prevent subrecords from being cleared by default
* Create a `person` authority with a `contact`
* Create a `collectionobject` with the `person` assigned to one of its fields
* Edit the `collectionobject` and pivot to the `person` with the mouse over using save and continue
* Check that the `contact` has been loaded for the `person` and that the `person` can be saved without error
This prevents necessary subrecord data from being removed from the redux store after records are saved. I added a boolean to `clear` for the case when we need to clear subrecord data there, otherwise any subrecords that are safe to clear are handled in `clearFiltered` during the iteration of the store …
> DRYD-1185: Error on save when pivoting to record

- src/helpers/objectHelpers.js
- test/specs/helpers/objectHelpers.spec.js
Jira: https://collectionspace.atlassian.net/browse/DRYD-1008
* Add check to avoid recursive operations with null values
The error in the search api came up with nested `BooleanConditionInputs` which assign their path a null value. This eventually causes an error when calling `Object.keys` w/ a null object during comparison of the search descriptors. I was initially considering removing the path from the class but it's used in a few places where I wasn't sure if there were any implications on removing it.
Also for replication of the issue, after executing the search I had to revise the search and update the terms. This way the search reducer will always run a diff on the given searchDescriptor and mostRecentSearchDescriptor.
> DRYD-1008: Add null check in flatten

- karma.conf.js
- src/components/sections/Footer.jsx
- styles/cspace-ui/Footer.css
- test/specs/components/sections/Footer.spec.jsx
- webpack.config.js
This displays build numbers (git commit hashes) along with the version information in the footer under certain conditions. The build numbers are displayed when the version of the services layer (as reported by the systeminfo endpoint) ends with "-SNAPSHOT", indicating that it is a development build. The build numbers are also displayed, regardless of the services version, in development builds of cspace-ui (such as when using `npm run devserver`).
This complements https://github.com/collectionspace/services/pull/320. When the services layer is configured to clone and build UI packages from source, it will be important to know the commit hash that is deployed, since the version number may not change.
**How should this be …
> Show build numbers in footer.

- README.md
This adds badges for CI build status and code coverage status back to the readme, now using GitHub Actions and Codecov instead of TravisCI and Coveralls.
This PR is mostly here to test the Codecov status checks on PRs. It also adds some useful information to the readme.
The CI status and Coverage status badges should appear on the readme.
None.
This is an update to the docs!
@ray-lee checked that the badges look good, and that the codecov status checks and comment are …
> Update readme badges.

- .github/workflows/ci.yml
- karma.conf.js
- test/specs/actions/account.spec.js
- test/specs/actions/authority.spec.js
- test/specs/actions/authz.spec.js
- test/specs/actions/batch.spec.js
- test/specs/actions/cspace.spec.js
- test/specs/actions/export.spec.js
- test/specs/actions/idGenerator.spec.js
- test/specs/actions/login.spec.js
- test/specs/actions/logout.spec.js
- test/specs/actions/partialTermSearch.spec.js
- test/specs/actions/record.spec.js
- test/specs/actions/relation.spec.js
- test/specs/actions/report.spec.js
- test/specs/actions/search.spec.js
- test/specs/actions/structuredDate.spec.js
- test/specs/actions/vocabulary.spec.js
- test/specs/components/record/RecordBrowser.spec.jsx
- test/specs/components/record/RelatedRecordBrowser.spec.jsx
- test/specs/containers/invocable/InvocationModalContainer.spec.jsx
- test/specs/containers/pages/ContentViewerPageContainer.spec.jsx
- test/specs/containers/pages/ExportViewerPageContainer.spec.jsx
- test/specs/containers/pages/ReportViewerPageContainer.spec.jsx
- test/specs/containers/record/RecordEditorContainer.spec.jsx
This adds Firefox to the browsers used for testing CI builds. Currently, only Chrome is used. It also increases the timeouts on some tests to reduce flakiness on Firefox, and changes the runner to Mac OS instead of Linux.
This partially restores the CI functionality we had on TravisCI/SauceLabs, now running on GitHub. Since Firefox is a supported browser, we should ensure that all tests succeed in it. It's more likely that users will be on Mac than Linux, so changing the runner to Mac creates a test environment that is more similar to an actual runtime environment.
https://collectionspace.atlassian.net/browse/DRYD-1223
https://collectionspace.atlassian.net/browse/DRYD-1227
**How should this be tested? Do these changes have …
> DRYD-1223, DRYD-1227: Add Firefox to CI builds.

- test/specs/actions/account.spec.js
- test/specs/actions/authority.spec.js
- test/specs/actions/authz.spec.js
- test/specs/actions/batch.spec.js
- test/specs/actions/cspace.spec.js
- test/specs/actions/export.spec.js
- test/specs/actions/idGenerator.spec.js
- test/specs/actions/login.spec.js
- test/specs/actions/logout.spec.js
- test/specs/actions/partialTermSearch.spec.js
- test/specs/actions/record.spec.js
- test/specs/actions/relation.spec.js
- test/specs/actions/report.spec.js
- test/specs/actions/search.spec.js
- test/specs/actions/structuredDate.spec.js
- test/specs/actions/vocabulary.spec.js
- test/specs/components/notification/Notification.spec.jsx
- test/specs/components/record/RecordBrowser.spec.jsx
- test/specs/components/record/RelatedRecordBrowser.spec.jsx
- test/specs/containers/invocable/InvocationModalContainer.spec.jsx
- test/specs/containers/pages/ContentViewerPageContainer.spec.jsx
- test/specs/containers/pages/ExportViewerPageContainer.spec.jsx
- test/specs/containers/pages/ReportViewerPageContainer.spec.jsx
- test/specs/containers/record/RecordEditorContainer.spec.jsx
This removes calls to `this.setTimeout` in tests (mostly in `before` hooks), that were setting the timeout to 3 seconds. These aren't needed, because we globally set the timeout to 4 seconds in karma.conf.js: https://github.com/collectionspace/cspace-ui.js/blob/2fa50d52ec55293669c3d0de7091b204f28fb8fb/karma.conf.js#L56-L60
This helps the tests to be less flaky in Firefox. Setting up the http server stub in the `before` hooks sometimes takes a long time on Firefox, and occasionally can exceed the 3 second timeout. This allows the 4 second global setting to take effect, which will hopefully be enough to prevent timeout failures.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1223
**How should this be tested? Do …
> Remove test timeouts that were set to 3 seconds.

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/collectionobject/messages.js
Adds chronology fields to collectionobject
The fields are defined in the spec for [DRYD-1133](https://collectionspace.atlassian.net/jira/software/c/projects/DRYD/issues/DRYD-1133).
* Build collectionspace
* Using the adjacent PR from cspace-ui, try to create and save a collectionobject with new fields:
* objectProductionEra
* assocControlledEventName
* assocControlledEventType
None
No
@mikejritter tested that the 3 fields listed save and load
> DRYD-1133: Add controlled chronology fields to collectionobject

- docs/configuration/README.md
- docs/configuration/VocabularyConfiguration.md
- src/helpers/configHelpers.js
- src/index.jsx
- test/specs/helpers/configHelpers.spec.jsx
This adds a top-level `disableAltTerms` setting to the UI config (default false). This setting has the same effect as the `disableAltTerms` setting in the config for a vocabulary, but it applies to all vocabularies. The `disableAltTerms` setting in a vocabulary remains. If it is set, it overrides the top-level setting, for that vocabulary.
This makes it easy to make alternate terms unselectable globally, without having to add configuration to every vocabulary.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1081
- In the index.html for a tenant, add the configuration setting `disableAltTerms: true`.
- Create a Person record with a Display Name …
> DRYD-1081: Add top-level disableAltTerms setting.

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/place/vocabularies.js
* Add archaeological site to place authority
* Add fieldCollectionSites to collectionobjects
Jira: https://collectionspace.atlassian.net/browse/DRYD-1217
* Create a place authority of type archaeological site
* Create a new collectionobject with a fieldCollectionEvent
* Reload the collectionobject and ensure that the fieldCollectionEvent persisted
This doesn't contain the associated authorities, which will be added at a later date
No
@mikejritter tested that the new …
> DRYD-1217: Archaeological site

- src/components/record/MiniViewPopupAutocompleteInput.jsx
This fixes a bug in the `MiniViewPopupAutocompleteInput` component that was updating the component state by assigning to `this.state` directly, instead of calling `setState`. This was always an incorrect usage of the React API, but it didn't cause any visible problems until we upgraded to React 16.
The incorrect state caused the popup not to open after the value in the autocomplete input was changed.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1236
- Create a new Group.
- Enter a value in the Group Owner field (either select an existing term, or create a new one).
- Hover the mouse pointer over the field.
A pop-up should appear, showing …
> DRYD-1236: Fix miniview popup not appearing after autocomplete value changes.

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
* Adds apparel size and descriptionLevel fields to collectionobject
* Adds apparel size and descriptionLevel to default collectionobject form
Jira: https://collectionspace.atlassian.net/browse/DRYD-1214
This is a field which existed in the OHC profile was was requested to be brought into core
* Rebuild and run collectionspace
* Create a collectionobject with an apparel size(s)
* Reload the collectionobject to ensure the save completed successfully
None
No
**Did someone actually run this code to verify it …
> DRYD-1213,DRYD-1214: Add description level and apparel size fields

- src/actions/authority.js
- src/components/login/LoginForm.jsx
This makes a few improvements to the handling of errors during login:
- When a specific error message is not found for an error code, fall back to a generic error message. This prevents react-intl from displaying a confusing/unhelpful message ("An id must be provided to format a message").
- Add an error message for the ERR_BAD_REQUEST error code.
- When retrieving vocabularies for authorities as part of login, ignore any 404 Not Found responses. This likely means the authority doesn't exist for the tenant, but is still configured and enabled in the UI config. This is generally fine, and shouldn't fail the login.
I ran into the aforementioned unhelpful react-intl error during login when running master against an older …
> Improve login error handling.

- docs/developer/BuildScripts.md
- docs/developer/GettingStarted.md
- index.html
- package-lock.json
- package.json
- webpack.config.js
- webpackDevServerConfig.js
This adds a `back-end` option to the devserver script that establishes a proxy to a back-end CollectionSpace server. This allows the UI under development to connect to a remote server, regardless of the CORS settings on that server. It also allows the UI under development to easily use the configuration from a remote server, without needing to reproduce that configuration in the local index.html file.
This makes it easier to test changes under development against configurations and data from remote CollectionSpace servers, without needing to manage CORS settings on those servers. It will be especially important for hosted clients who want to develop plugins, and see them run against their staging or production sites.
JIRA: …
> DRYD-1226: Add proxy feature to devserver.

- src/components/invocable/InvocationEditor.jsx
- src/components/invocable/InvocationModal.jsx
- src/components/record/RecordBatchPanel.jsx
- src/components/record/RecordReportPanel.jsx
- test/specs/components/invocable/InvocationEditor.spec.jsx
- test/specs/components/record/RecordBatchPanel.spec.jsx
- test/specs/components/record/RecordReportPanel.spec.jsx
This changes the report and batch job sidebars on group records to show items that have either `supportsSingleDoc`=`true` and `forDocType`=`Group`, or `supportsGroup`=`true` (regardless of `forDocType`). Previously, only items with `supportsSingleDoc`=`true` and `forDocType`=`Group` were shown.
This allows reports and batch jobs that are runnable in group mode to appear in the sidebar of group records, without needing to also set `forDocType` to `group`. Setting `supportsGroup` to true should be sufficient for getting a report/batch job to appear in the sidebar for Group records.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1069
- Open a …
> DRYD-1069: Show all supportsGroup invocables in group record sidebar.

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/collectionobject/messages.js
* Update assocEvent to be repeatable
* Remove assocEventType
* Add controlled contentEvent
Changes requested for assocEvent, including adding contentEvent.
Jira: https://collectionspace.atlassian.net/browse/DRYD-1238
* Build cspace with fcart enabled
* Test that assocEvent is repeatable and can use `chronology/event` and `chronology/era`
* Test that contentEvent is repeatable and can use `chronology/event` and `chronology/era`
Application layer PR is required
No
**Did someone actually run this code to verify it …
> DRYD-1238: Controlled event fields for collectionobject

- src/plugins/extensions/core/fields.js
Adds field definition for collectionspace_core uri so that it can be selected in drop downs when exporting data.
As part of [DRYD-1080](https://collectionspace.atlassian.net/jira/software/c/projects/DRYD/issues/DRYD-1080), we want to be able to export the uri in order to make operations for other components easy. The work was completed in the services layer but no support was added in order to do this from the ui as well. Adding the field definition allows the uri to be picked up when choosing what fields to export.
* Start the devserver: `npm run devserver`
* If no objects/procedures/authorities exist, create one
* Search for newly created record
* Use …
> DRYD-1080: Display uri in export list

- src/components/search/SearchPanel.jsx
- src/containers/search/SearchPanelContainer.js
This correctly connects the `searchError` prop of the `SearchPanel` component to state from the Redux store. Previously, `searchError` was not being set, even though it was needed for proper functioning of the `SearchPanel`. It also tweaks the conditions under which `SearchPanel` executes a new search.
This fixes a bug where the `SearchPanel` would issue a new search whenever a search resulted in an error. When the error was a 401 due to not being logged in, this would cause an endless loop of searches.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1259
- Log in using the UI
- Do a keyword search on a record type
- Open the Network panel in …
> DRYD-1259: Fix repeated search panel requests when login has expired.

- package-lock.json
- package.json
- src/components/pages/service/PasswordResetRequestPage.jsx
- src/components/pages/service/ServiceLoginPage.jsx
- src/plugins/recordTypes/account/fields.js
- src/plugins/recordTypes/account/forms/default.jsx
- src/service.jsx
- styles/cspace-ui/ServicePage.css
This adds support for single-sign on. (Currently the services layer only supports SSO via SAML, but the UI is intended to be agnostic to the SSO protocol).
- The login screen presented by the services layer now includes links to log in with the configured SSO providers (if any).
- The account screen now displays the Require Single Sign-on field (a checkbox). When a new user is created, and Require SSO is checked, the password/confirm password fields are allowed to be empty.
CSpace 8.0 supports SSO with SAML. This exposes that functionality to users.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1244
For each SSO provider that has been …
> DRYD-1244: Add SSO support.

- package-lock.json
- package.json
- src/actions/cspace.js
- src/actions/login.js
- src/components/pages/AuthorizedPage.jsx
- src/containers/pages/AuthorizedPageContainer.js
- src/reducers/user.js
- test/specs/reducers/user.spec.js
This fixes a bug (introduced with the Spring Security upgrade/switch to OAuth authorization code grant) where the logged in user is not updated properly in the redux store. This resulted in unnecessary re-authorization when a valid stored token was present.
This is part of the Spring Security upgrade: https://collectionspace.atlassian.net/browse/DRYD-1242
Log in, browse to a record, and reload the browser. Upon reload, re-authorization should not occur (there is no request to the /cspace-services/oauth2/authorize endpoint, and no resulting redirect to the /authorized page in the UI).
None.
**Has the …
> DRYD-1242: Fix unnecessary re-authorization.

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/collectionobject/forms/photo.jsx
- src/plugins/recordTypes/collectionobject/forms/public.jsx
- src/plugins/recordTypes/collectionobject/forms/timebased.jsx
Adds fields and updates the default form for object count fields
Jira: https://collectionspace.atlassian.net/browse/DRYD-1316
This is intended to replace the `numberOfObjects` field with a more complete set of fields to support reporting needs for archaeology and NAGPRA profiles. 
* Rebuild collectionspace
* See that the new term list exists under `objectcounttypes`
* Create a collectionobject using the new fields and term
We'll need to double check that the layout is what was expected. I wasn't sure which one was being used for the wireframes, and wanted to get this up to make testing the …
> DRYD-1316: Add object count group fields

- src/plugins/recordTypes/organization/fields.js
- src/plugins/recordTypes/organization/forms/default.jsx
Adds nameNote to organization authority
Jira: https://collectionspace.atlassian.net/browse/DRYD-1206
This adds a field to the organization authority to store information about the authority.
* Rebuild collectionspace
* Create an organization authority with the nameNote filled out
* Verify the field saves
None
No
@mikejritter tested locally
> DRYD-1206: Add nameNote field

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/collectionobject/forms/photo.jsx
- src/plugins/recordTypes/collectionobject/forms/public.jsx
- src/plugins/recordTypes/collectionobject/forms/timebased.jsx
- test/specs/helpers/searchHelpers.spec.js
* Updates object count group layout to be tabular
* Removes numberOfObjects
This is a combination of 2 jiras:
* https://collectionspace.atlassian.net/browse/DRYD-1374
* https://collectionspace.atlassian.net/browse/DRYD-1379
The first is making updates to the layout for the new object count group so that it is tabular and has its note inline. This comes from feedback that the larger note field is not necessary for this set of fields.
The second is removing numberOfObjects, which is being done because the field is being replaced by objectCount.
* Run npm test + npm lint
* View the new object count group layout
* Observer that …
> Update ObjectCountGroup layout

- src/plugins/extensions/associatedAuthority/fields.js
- src/plugins/extensions/associatedAuthority/form.jsx
* Adds assoc prefix to associated authorities fields
Jira: https://collectionspace.atlassian.net/browse/DRYD-1286
This helps with fields in the schema which may have the same name, e.g. `chronologies_common.chronologyNote` and `assocCronlogyAuthGroupList/assocChronologyAuthGroup.chronlogyNote`. By adding a prefix we're removing the possibility of this collision, as we will have `assocChronlogyAuthGroupList/assocChronologyAuthGroup.assocChronlogyNote`.
* Using the PR from the application layer: https://github.com/collectionspace/application/pull/275
* Verify that associated authorities can be saved
**Dependencies for merging? …
> Associated Authority Field Prefix

- docs/configuration/RecordSidebarConfiguration.md
Captures some of the information about record sidebar configuration surfaced in Slack conversation
To clarify scope of record sidebar config vs. mediaSnapshotSort 
n/a
n/a
Yep. 😄 
n/a
> Clarify record sidebar configuration documentation page

- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/collectionobject/forms/inventory.jsx
- src/plugins/recordTypes/collectionobject/forms/photo.jsx
- src/plugins/recordTypes/collectionobject/forms/public.jsx
- src/plugins/recordTypes/collectionobject/forms/timebased.jsx
This updates the forms which were missing the controlled fields from 7.2. It also updates ordering of the fields so that the controlled field is display first in the row.
Jira: https://collectionspace.atlassian.net/browse/DRYD-1397
This is something I discovered while adding public browser data through the template and realized I never updated the other forms to include these fields.
* Create a collectionobject using...
* inventory template
* photo template
* public browser template
* time based media template
* See that the controlled object name and controlled material fields exist and display first
**Dependencies for merging? …
> Add Object Name Controlled and Material Controlled to Missing Forms

- src/plugins/extensions/associatedAuthority/fields.js
This updates many of the default messages for the associated authority fields. Mostly prefixing with 'Associated' in order to identify the fields in advanced searches, as well as adding `groupName` to structured date group fields for use in the group search.
Jira: https://collectionspace.atlassian.net/jira/software/c/projects/DRYD/issues/DRYD-1286
It was reported that when exporting authorities with the associated authorities block, certain fields were hard to differentiate, e.g. `Place note` would appear twice. I realized this was likely affecting the advanced search field and group context menus as well because they pull from the same set of messages. The updates to the messages have introduced a _tiny_ bit of redundancy …
> Assoicated Authority Message Updates

- src/plugins/recordTypes/acquisition/fields.js
- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/intake/fields.js
- src/plugins/recordTypes/loanin/fields.js
- src/plugins/recordTypes/loanout/fields.js
- src/plugins/recordTypes/objectexit/fields.js
- src/plugins/recordTypes/uoc/fields.js
* Set height to 23px for note fields in annotation and status groups
Jira: https://collectionspace.atlassian.net/browse/DRYD-1284
Jira: https://collectionspace.atlassian.net/browse/DRYD-1285
This is just a small styling tweak requested from feedback. I saw 23px defined in the dimensions for cspace-input and went with that for the size.
* View the note field in the following procedures
* acquisition - approval group
* collectionobject - annotation group
* intake - approval group
* loan in - loan status group
* loan out - loan status group
* object exist - deaccession approval group
* uoc - authorization group
**Dependencies for …
> Decrease multiline height for various fields

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
Adds repeating group for fieldCollectionPlace to collectionobject fields and form.
Jira: https://collectionspace.atlassian.net/browse/DRYD-1395
This updates filedCollectionPlace so that it can be repeatable, which was requested in the associated JIRA.
* Rebuild and start collectionspace
* Check that the field collection place shows as repeatable input
* Check that the field collection place can save and load input
None
No
@mikejritter tested against a …
> DRYD-1395: Make fieldCollectionPlace repeatable

- src/plugins/extensions/associatedAuthority/fields.js
Updates the source for related authorities to use assocauthorityrelationtype
Jira: https://collectionspace.atlassian.net/browse/DRYD-1286
This changes the term source related authorities to use the new assocauthorityrelationtype.
* Create one of chronology, person, or place
* Under Associated Authorities, fill out the form entries and see that the new term list is being populated by assocauthorityrelationtype
None
No
@mikejritter tested locally against …
> Change relation type to associated authority relation

- src/components/pages/SearchResultPage.jsx
- src/components/search/SearchResultSidebar.jsx
- src/components/search/SearchResultTitleBar.jsx
- styles/cspace-ui/SearchResultSidebar.css
- styles/cspace-ui/SidebarToggleBar.css
- styles/cspace-ui/TitleBar.css
- test/specs/components/search/SearchResultSidebar.spec.jsx
* Render the sidebar toggle button as part of the sidebar
* Update css to keep sidebar styling consistent with previous behavior
Jira: https://collectionspace.atlassian.net/browse/DRYD-1309
This issue came about from the wcag audit with respect to the logical ordering of elements when tabbing through the page. According to the audit the expected behavior is for the tab input to go through the search result table first, then navigate to the sidebar. The toggle bar for the sidebar was created before the sidebar which caused it to be tabbed to before the search result table, which is out of order according to the audit. 
* Test the …
> Update focus order for search result page

- src/components/pages/service/PasswordResetPage.jsx
- src/service.jsx
This changes the "Sign in" link displayed after a successful password reset to go to a tenant-specific URL supplied as a prop, instead of the service layer login page at `/cspace-services/login`. Typically, the prop should be set to the UI page that initiates an OAuth authorization attempt for the tenant, e.g. `/cspace/{tenant short name}/authorize`. 
If the prop is not provided, `/cspace-services/login` is used as a fallback.
After a password reset, a new OAuth authorization attempt should be started by going to the appropriate page in the UI, which will redirect to `/cspace-services/login` after setting up the correct state. Going directly to `/cspace-services/login` may pick up the state from a previous failed …
> DRYD-1417: Go to UI authorize page after password reset success.

- src/plugins/recordTypes/location/fields.js
* Fixes the condition group message id
Jira: https://collectionspace.atlassian.net/browse/DRYD-1424
This is an inconsistency in the field config which was noticed by Kristina.
Non-functional change so this isn't tested
None
No
@mikejritter ran `npm run lint` and `npm run test` as a sanity check
> Fix incorrect id

- src/plugins/recordTypes/concept/vocabularies.js
- src/plugins/recordTypes/index.js
- src/plugins/recordTypes/nagpraclaim/advancedSearch.js
- src/plugins/recordTypes/nagpraclaim/columns.js
- src/plugins/recordTypes/nagpraclaim/fields.js
- src/plugins/recordTypes/nagpraclaim/forms/default.jsx
- src/plugins/recordTypes/nagpraclaim/forms/index.js
- src/plugins/recordTypes/nagpraclaim/idGenerators.js
- src/plugins/recordTypes/nagpraclaim/index.js
- src/plugins/recordTypes/nagpraclaim/messages.js
- src/plugins/recordTypes/nagpraclaim/serviceConfig.js
- src/plugins/recordTypes/nagpraclaim/title.js
- test/specs/plugins/recordTypes/nagpraclaim/advancedSearch.spec.js
- test/specs/plugins/recordTypes/nagpraclaim/columns.spec.js
- test/specs/plugins/recordTypes/nagpraclaim/forms/default.spec.js
- test/specs/plugins/recordTypes/nagpraclaim/index.spec.js
- test/specs/plugins/recordTypes/nagpraclaim/messages.spec.js
- test/specs/plugins/recordTypes/nagpraclaim/serviceConfig.spec.js
- test/specs/plugins/recordTypes/nagpraclaim/title.spec.js
* Add NAGPRA claim procedure
* Add ethculture to concept authority as culture
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1330
* Run `npm run test` and `npm run lint` as a sanity check
* Rebuild and start collectionspace
* Create a NAGPRA Claim with all fields filled out and ensure it saves
`concept/culture` doesn't exist for core, need to figure out what authority to pull from for that field (or if it should be added to core)
No …
> DRYD-1330: NAGPRA Claim

- src/plugins/recordTypes/dutyofcare/fields.js
*Adds ulan sources to various authorities
Jira: https://collectionspace.atlassian.net/browse/DRYD-1332
I had staged these changes but forgot to add them when making the PR. This allows the fields which use the person and organization authorities to use the ulan authorities.
* npm run devserver --back-end=https://core.dev.collectionspace.org
* When creating a duty of care, see that the party, on behalf of, and determined by fields pull from the local and ulan authority types
None
No
**Did someone actually run …
> Update DutyOfCare authority sources

- src/plugins/recordTypes/index.js
- src/plugins/recordTypes/summarydocumentation/advancedSearch.js
- src/plugins/recordTypes/summarydocumentation/columns.js
- src/plugins/recordTypes/summarydocumentation/fields.js
- src/plugins/recordTypes/summarydocumentation/forms/default.jsx
- src/plugins/recordTypes/summarydocumentation/forms/index.js
- src/plugins/recordTypes/summarydocumentation/idGenerators.js
- src/plugins/recordTypes/summarydocumentation/index.js
- src/plugins/recordTypes/summarydocumentation/messages.js
- src/plugins/recordTypes/summarydocumentation/serviceConfig.js
- src/plugins/recordTypes/summarydocumentation/title.js
- test/specs/plugins/recordTypes/summarydocumentation/advancedSearch.spec.js
- test/specs/plugins/recordTypes/summarydocumentation/columns.spec.js
- test/specs/plugins/recordTypes/summarydocumentation/forms/default.spec.js
- test/specs/plugins/recordTypes/summarydocumentation/index.spec.js
- test/specs/plugins/recordTypes/summarydocumentation/messages.spec.js
- test/specs/plugins/recordTypes/summarydocumentation/serviceConfig.spec.js
- test/specs/plugins/recordTypes/summarydocumentation/title.spec.js
* Add summary documentation procedure
Jira: https://collectionspace.atlassian.net/browse/DRYD-1333
This adds the summary documentation procedure which is a necessary part of nagpra workflows.
* Ensure the linting and test pass
* `npm run lint`
* `npm run tests`
* Start the devserver
* Create a summary documentation and ensure it saves
* Check that the search results for summary documentation display correctly
* Check the advanced search fields for any messages which look incorrect
None
No
**Did someone actually run this code to …
> DRYD-1333: Summary Documentation

- styles/cspace-ui/BannerMain.css
- styles/cspace-ui/Logo.css
* Adds a border to the CollectionSpace logo when focused
Jira: https://collectionspace.atlassian.net/browse/DRYD-1307
The CollectionSpace logo was one of the few elements without any focus indicators. This updates the css so that it will get a similar border to that of other input elements with a rounded border. The overflow rule in the banner is removed so that the outline displays properly as the logo is at the boundaries of the banner.
* Log in to CollectionSpace and tab or shift tab until the focus is on the CollectionSpace logo
* See that the border shows, indicating that the logo is the focused element …
> DRYD-1307: Focus indicator for CollectionSpace logo

- docs/configuration/messages.js
- src/containers/input/DateInputContainer.jsx
* Adds a tooltip prop to DateInput
* Add title to LineInput to display provided tooltips
Jira: https://collectionspace.atlassian.net/browse/DRYD-1305
This is the second PR for adding instructions for the DateInput. It informs the user that the down arrow can be used as well as the mouse in order to open up the calendar. I mentioned in the other PR that this likely needs to be done for other components as well, such as the TermPicker, OptionPicker, and StructuredDate inputs.
* Run `npm run lint` and `npm run test` to ensure nothing broke
* Rebuild and deploy alongside the cspace-input PR
* Mouseover a DateInput and …
> DRYD-1305: Instructions for DateInput

- src/plugins/recordTypes/heldintrust/columns.js
- src/plugins/recordTypes/heldintrust/fields.js
- src/plugins/recordTypes/heldintrust/forms/default.jsx
- src/plugins/recordTypes/heldintrust/idGenerators.js
- src/plugins/recordTypes/heldintrust/messages.js
- src/plugins/recordTypes/heldintrust/serviceConfig.js
- src/plugins/recordTypes/heldintrust/title.js
- src/plugins/recordTypes/index.js
- test/specs/plugins/recordTypes/heldintrust/columns.spec.js
- test/specs/plugins/recordTypes/heldintrust/title.spec.js
* Update Held-in-Trust for NAGPRA workflows
Jira: https://collectionspace.atlassian.net/browse/DRYD-1358
This updates the Held-in-Trust procedure which was going to be added for 8.0 to be compatible with NAGPRA related workflows. It 
* Run `npm run lint` and `npm run tests`
* Rebuild collectionspace with the core tenant enabled
* Start collectionspace
* Start the devserver `npm run devserver`
* Check that the Held-in-Trust procedure saves and loads as expected
* With the exception of heldintrust type which needs default terms
* Optionally check the messages in the advanced search
None
**Has the …
> DRYD-1358: Update Held-in-Trust

- src/plugins/recordTypes/heldintrust/fields.js
- src/plugins/recordTypes/heldintrust/forms/default.jsx
- src/plugins/recordTypes/heldintrust/messages.js
* Adds cultural care to Held-in-Trust
Jira: https://collectionspace.atlassian.net/browse/DRYD-1358
Instead of creating a new CulturalCare procedure, we're opting to pull the cultural care fields directly into Held-in-Trust. This pulls in the fields and form from `cspace-ui-plugin-ext-culturalcare.js` with updates to be for heldintrust rather than collectionobject.
* Start the devserver `npm run devserver`
* Create a Held-in-Trust record with the cultural care information filled out 
None
**Has the application documentation been updated for …
> DRYD-1358: Held-in-Trust Updates

- src/plugins/recordTypes/consultation/advancedSearch.js
- src/plugins/recordTypes/consultation/columns.js
- src/plugins/recordTypes/consultation/fields.js
- src/plugins/recordTypes/consultation/forms/default.jsx
- src/plugins/recordTypes/consultation/forms/index.js
- src/plugins/recordTypes/consultation/idGenerators.js
- src/plugins/recordTypes/consultation/index.js
- src/plugins/recordTypes/consultation/messages.js
- src/plugins/recordTypes/consultation/serviceConfig.js
- src/plugins/recordTypes/consultation/title.js
- src/plugins/recordTypes/index.js
- test/specs/plugins/recordTypes/consultation/advancedSearch.spec.js
- test/specs/plugins/recordTypes/consultation/columns.spec.js
- test/specs/plugins/recordTypes/consultation/forms/default.spec.js
- test/specs/plugins/recordTypes/consultation/index.spec.js
- test/specs/plugins/recordTypes/consultation/messages.spec.js
- test/specs/plugins/recordTypes/consultation/serviceConfig.spec.js
- test/specs/plugins/recordTypes/consultation/title.spec.js
* Add consultation recordtype
* Add tests for consultation record
Jira: https://collectionspace.atlassian.net/browse/DRYD-1390
The consultation procedure is part of the 8.1 updates for improving NAGPRA workflows. It adds the ability to document the consultation process itself. 
* Start collectionspace using the related services and application PRs
* Create and save a consultation
* Use the advanced search and check that field names make sense
None
**Has the application documentation been updated for …
> DRYD-1390: Consultation

- src/plugins/recordTypes/collectionobject/fields.js
* Removes default values for dynamic term lists
Jira: https://collectionspace.atlassian.net/browse/DRYD-1447
A user is able to remove the default values from the sources (`publishto` and `inventorystatus`), which causes the display in the field to be invalid. Note - the ticket mentions `recordStatus` but that field is controlled by an option picker. I believe it was just a typo, and should have been `publishTo`.  
* Run the devserver, e.g. `npm run devserver --back-end=https://core.dev.collectionspace.org`
* Go to create a collectionobject and see that the `Publish to` and `Inventory status` fields do not have default values
**Dependencies for merging? …
> DRYD-1447: Remove default values for dynamic term lists

- src/plugins/recordTypes/consultation/fields.js
* Remove ulan from autocomplete sources
* Relabel party involved name to person
* Relabel consultParty to recipient
Jira: https://collectionspace.atlassian.net/browse/DRYD-1390
These are changes requested based on preliminary testing of the consultation procedure. Fairly minor requests - just removing ulan from sources so they only use the `{person,org}/local` authority and some relabeling of fields.
* See that the autocomplete sources for `involvedParty`, `involvedOnBehalfOf`, and `consultParty` are restricted to local authorities
* See updates labels for `involvedParty` and `consultParty`
**Dependencies for merging? Releasing to …
> Consultation Updates

- src/components/pages/RootPage.jsx
- src/service.jsx
* Set the lang attribute
Jira: https://collectionspace.atlassian.net/browse/DRYD-1311
This is part of the wcag focused work, and adds the lang attribute to the html tag through helmet. 
* Run the devserver, e.g.
```
npm run devserver --back-end=https://core.dev.collectionspace.org
```
* Inspect the page and look at the `<html>` tag
* Ensure the `lang` attr is set to the current locale
Currently this doesn't update the SSO login, logout, and password reset pages. I tried to update the pages themselves, as well as `service.jsx`, but none would add the lang attr. Still investigating what's going on …
> DRYD-1311: Set lang attr

- src/plugins/recordTypes/dutyofcare/advancedSearch.js
- src/plugins/recordTypes/dutyofcare/columns.js
- src/plugins/recordTypes/dutyofcare/fields.js
- src/plugins/recordTypes/dutyofcare/forms/default.jsx
- src/plugins/recordTypes/dutyofcare/messages.js
- src/plugins/recordTypes/dutyofcare/serviceConfig.js
- src/plugins/recordTypes/dutyofcare/title.js
- test/specs/plugins/recordTypes/dutyofcare/title.spec.js
* Fix pluralization for duty of care
* Remove ulan from various sources
* Update involvedParty label
* Rename title to dutyOfCareTitle
Jira: https://collectionspace.atlassian.net/browse/DRYD-1332
These changes come from the testing done against Duty of Care. It changes the pluralization used in the ui and the schema, and updates the involvedParty label. I also noticed that the `title` was not always being pulled correctly from the services layer so it has been renamed to `dutyOfCareTitle`.
* Run `npm run lint` and `npm run test`
* Rebuild the other PRs and start collectionspace
* Start the devserver, `npm run devserver`
* Check that the Duty of Care …
> Duty of Care Updates

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/collectionobject/forms/public.jsx
* Add related link group to collectionobject
Jira: https://collectionspace.atlassian.net/browse/DRYD-1436
This adds related links to the reference information section for collectionobjects.
* Rebuild collectionspace using the related application PR
* Run the devserver (`npm run devserver`) 
* Create a collectionobject and scroll to the Reference Information section
* See that the related link group exists and can be filled out
* Switch to the public browser template and see the same as the above
None
No
**Did someone actually run …
> DRYD-1436: Add related link group

- src/plugins/recordTypes/heldintrust/fields.js
* Removes ulan from sources
* Update agreementGroup to use deaccessionapprovalgroup
* Update agreementStatus to use deaccessionapprovalstatus
* Update labels to use Held-in-Trust
Jira: https://collectionspace.atlassian.net/browse/DRYD-1358
This has the changes requested from initial testing that Jessi and Jadeen did on the new procedure. It's mostly minor changes involving relabeling fields and updating sources for terms and autocomplete fields.
* Ensure all tests continue to pass: `npm run lint` and `npm run test`
* See that the changes exist:
* `Agreement approval` should become `Held-in-Trust status`
* …
> Held-in-Trust QA Updates

- src/plugins/recordTypes/summarydocumentation/columns.js
- src/plugins/recordTypes/summarydocumentation/fields.js
- src/plugins/recordTypes/summarydocumentation/forms/default.jsx
* Remove ulan from sources
* Remove tgn from sources
* Update statusGroupType to be a TermPickerInput
* Add archculture to culture source
* Use nagpradocumentationstatus for statusGroup.status source
* Rename culturalAffiliationGroup to affiliationGroup
* Relabel some fields
* Fix incorrect field name
Jira: https://collectionspace.atlassian.net/browse/DRYD-1333
These are changes that came from the initial testing that Jessi and Jadeen did.
* Rebuild and start collectionspace
* Run `npm run lint` and `npm run test`
* Start the devserver
* Create a Summary Documentation procedure and see the changes to the form are as expected
* Search for Summary …
> SummaryDocumentation QA Updates

- src/plugins/recordTypes/repatriationclaim/fields.js
- src/plugins/recordTypes/repatriationclaim/messages.js
* Remove ulan and tgn from sources
* Relabel fields
* Claim Status use deaccessionapprovalstatus
* Claim Documentation Group use doumentationgroup
* Cultural Group pull from both archculture and ethculture
Jira: https://collectionspace.atlassian.net/browse/DRYD-1330
These are changes that came from the first pass of QA testing. Fairly minor changes, just updating sources for fields and updating labels.
* Check that `npm run lint` and `npm run test` still pass
* Run the devserver `npm run devserver --back-end=https://core.dev.collectionspace.org`
* Create a claim and see the update fields and sources …
> Claim QA Updates

- src/plugins/recordTypes/concept/vocabularies.js
* Relabel culture authorities
Jira: https://collectionspace.atlassian.net/browse/DRYD-1495
This is to update the label of ethculture to cultural group, which makes more sense conceptually with how it works. I also noticed that archculture was labeled differently compared to anthro so I adjusted it to be in line with that.
* Run the devserver `npm run devserver --back-end=https://core.dev.collectionspace.org`
* Check that ethculture and archculture display their updated labels
None
No
**Did someone actually run this code to verify …
> DRYD-1495: Relabel culture authorities

- src/plugins/recordTypes/chronology/columns.js
* Fixes typo in field names for chronology search
Jira: https://collectionspace.atlassian.net/browse/DRYD-1517
This fixes a bug when searching on Chronology authorities. Currently the wrong field is being used, so `ERR_API` is being returned in the search form (a 400 from the back end). This is being caused by the terms having the wrong name (citationTermGroupList), which does not exist in the chronology schema.
* Run the devserver, e.g. `npm run devserver --back-end https://core.dev.collectionspace.org`
* Search on Chronology authorities
* Use the sort functionality to sort by display name and term status
**Dependencies for merging? Releasing to …
> DRYD-1517: Chronology Search Sort Order

- src/plugins/recordTypes/deaccession/advancedSearch.js
- src/plugins/recordTypes/deaccession/columns.js
- src/plugins/recordTypes/deaccession/fields.js
- src/plugins/recordTypes/deaccession/forms/default.jsx
- src/plugins/recordTypes/deaccession/forms/index.js
- src/plugins/recordTypes/deaccession/idGenerators.js
- src/plugins/recordTypes/deaccession/index.js
- src/plugins/recordTypes/deaccession/messages.js
- src/plugins/recordTypes/deaccession/serviceConfig.js
- src/plugins/recordTypes/deaccession/title.js
- src/plugins/recordTypes/index.js
- test/specs/plugins/recordTypes/deaccession/advancedSearch.spec.js
- test/specs/plugins/recordTypes/deaccession/columns.spec.js
- test/specs/plugins/recordTypes/deaccession/forms/default.spec.js
- test/specs/plugins/recordTypes/deaccession/index.spec.js
- test/specs/plugins/recordTypes/deaccession/messages.spec.js
- test/specs/plugins/recordTypes/deaccession/serviceConfig.spec.js
- test/specs/plugins/recordTypes/deaccession/title.spec.js
* Create deaccession procedure
* Add deaccession tests
Jira: https://collectionspace.atlassian.net/browse/DRYD-1355
The Deaccession procedure adds the ability to capture the decision making around removing an accessioned object. Previously this was part of the ObjectExit procedure, and this is breaking it out into it's own data structure. 
* Rebuild and start collectionspace
* Run `npm run test` and `npm run lint`
* Start the devserver `npm run devserver`
* Create a deaccession procedure and ensure it saves and loads
* Use the advanced search for a deaccession procedure and check that all messages make sense
**Dependencies for merging? Releasing to …
> DRYD-1355: Deaccession Procedure

- src/actions/search.js
- src/components/record/RecordSidebar.jsx
- src/components/record/RelatedRecordPanel.jsx
- test/specs/components/record/RelatedRecordPanel.spec.jsx
* Allow for multiple related records panels
* Add serviceTag for querying on sets of records
Jira: https://collectionspace.atlassian.net/browse/DRYD-1393
This is a WIP atm I'll update later with a full description
* Add a sidebar.js (e.g. `heldintrust/sidebar.js`)
```
export default {
relatedRecords: [{
recordType: 'collectionobject',
}, {
recordType: 'procedure',
serviceTag: '-nagpra',
}, {
id: 'nagpra',
recordType: 'procedure',
serviceTag: 'nagpra',
}],
};
```
* Update the index.js to include the sidebar
* Add a message for the new record panel to messages.js
```
sidebar: defineMessages({
nagpra: {
id: 'panel.heldintrust.nagpra',
defaultMessage: …
```
> DRYD-1393: Support Multiple Related Record Sidebars

- src/components/search/SearchResultTable.jsx
- test/specs/components/search/SearchResultTable.spec.jsx
* Sets the row label using the data from the highest order column
Jira:
* https://collectionspace.atlassian.net/browse/DRYD-1308
* https://collectionspace.atlassian.net/browse/DRYD-1310
The labels were previously only 'row' which is not descriptive of the row itself. This adds a label based on the example DRYD-1308 to each row in the SearchResultTables.
* Run `npm run devserver --back-end=https://core.dev.collectionspace.org`
* Run a search and look at the resulting table
* For each row, an aria-label should exist that reads something like `{primary-column-data} selected row {index} of {total}`
* …
> Set row aria-label for search results

- src/plugins/recordTypes/heldintrust/fields.js
* Fix typo in requester display
Jira: https://collectionspace.atlassian.net/browse/DRYD-1550
* Run the devserver with core as a backend `npm run devserver --back-end=https://core.dev.collectionspace.org`
* Create a Held-in-Trust record and see 'Requester' spelled correctly
* In the advanced search interface, check the 'Access limitation requester' is spelled correctly
None
No
@mikejritter tested with core.dev as a backend
> DRYD-1550: Fix typo in requester display name

- src/plugins/recordTypes/nagprainventory/fields.js
* Fixes the label used for era in NAGPRA Inventory
Jira: https://collectionspace.atlassian.net/browse/DRYD-1331
This was a typo noticed during QA
* Run the devserver: `npm run devserver --back-end=https://core.dev.collectionspace.org`
* Create a NAGPRA Inventory and check that the `Time period` field is labelled `Era`
* In the advanced search, check that `Time period era` shows up in the field search
None
No
@mikejritter tested with core.dev as a backend
> Fix time period era label

- src/plugins/recordTypes/exit/advancedSearch.js
- src/plugins/recordTypes/exit/columns.js
- src/plugins/recordTypes/exit/fields.js
- src/plugins/recordTypes/exit/forms/default.jsx
- src/plugins/recordTypes/exit/forms/index.js
- src/plugins/recordTypes/exit/idGenerators.js
- src/plugins/recordTypes/exit/index.js
- src/plugins/recordTypes/exit/messages.js
- src/plugins/recordTypes/exit/serviceConfig.js
- src/plugins/recordTypes/exit/title.js
- src/plugins/recordTypes/index.js
- src/plugins/recordTypes/objectexit/messages.js
- test/specs/plugins/recordTypes/exit/advancedSearch.spec.js
- test/specs/plugins/recordTypes/exit/columns.spec.js
- test/specs/plugins/recordTypes/exit/forms/default.spec.js
- test/specs/plugins/recordTypes/exit/index.spec.js
- test/specs/plugins/recordTypes/exit/messages.spec.js
- test/specs/plugins/recordTypes/exit/serviceConfig.spec.js
- test/specs/plugins/recordTypes/exit/title.spec.js
* Add Exit service for new ObjectExit workflow
* Add Exit client
* Add ExitValidationHandler
* Add xsd for exits_common schema
Jira: https://collectionspace.atlassian.net/browse/DRYD-1356
The existing Object Exit procedure is being deprecated in favor of it being split into two procedures - the Deaccession and Object Exit. This handles the creation of a new Object Exit, named Exit, which will replace existing use.
* Pull the related services and application PRs
* Rebuild and deploy collectionspace with the required tenants enabled for running the integration tests
* Run the devserver: `npm run …
> DRYD-1356: New ObjectExit Procedure

- src/plugins/recordTypes/index.js
- src/plugins/recordTypes/restrictedmedia/advancedSearch.js
- src/plugins/recordTypes/restrictedmedia/columns.js
- src/plugins/recordTypes/restrictedmedia/fields.js
- src/plugins/recordTypes/restrictedmedia/forms/default.jsx
- src/plugins/recordTypes/restrictedmedia/forms/index.js
- src/plugins/recordTypes/restrictedmedia/idGenerators.js
- src/plugins/recordTypes/restrictedmedia/index.js
- src/plugins/recordTypes/restrictedmedia/messages.js
- src/plugins/recordTypes/restrictedmedia/optionLists.js
- src/plugins/recordTypes/restrictedmedia/serviceConfig.js
- src/plugins/recordTypes/restrictedmedia/subrecords.js
- src/plugins/recordTypes/restrictedmedia/title.js
- test/specs/plugins/recordTypes/restrictedmedia/fields.spec.js
- test/specs/plugins/recordTypes/restrictedmedia/index.spec.js
- test/specs/plugins/recordTypes/restrictedmedia/title.spec.js
* Add RestrictedMedia record type
* Add RestrictedMedia tests
Jira: https://collectionspace.atlassian.net/browse/DRYD-1399
This adds record type for RestrictedMedia, which is intended for use in workflows where there may be sensitive media which should not be immediately accessible. 
* Test that the restrictedmedia resource can save and upload blobs
This will eventually need a new type of view for the blob to prevent the thumbnail from automatically showing.
**Has the application documentation been …
> DRYD-1399: RestrictedMedia

- src/components/pages/CreatePage.jsx
- styles/cspace-ui/CreatePagePanel.css
* Bold the Tag header for nested procedure lists
* Update Tag headers to include 'Procedure'
* Replace groupBy function
Jira: https://collectionspace.atlassian.net/browse/DRYD-1351
These are changes requested for the Create Page from the associated JIRA. Mostly minor changes - I was thinking about trying something more clever with the messages but kept it simple.
* Run the devserver with dev as a backend, e.g.
```
npm run devserver --back-end=https://core.dev.collectionspace.org
```
* Navigate to the Create New page
* See that the nested lists for Procedures are bolded
* See that the nested lists for Procedures include 'Procedures', e.g. 'NAGPRA …
> Create UI css updates

- src/plugins/recordTypes/exit/columns.js
- src/plugins/recordTypes/heldintrust/columns.js
- src/plugins/recordTypes/summarydocumentation/columns.js
- test/specs/plugins/recordTypes/exit/columns.spec.js
* Fix name for exit owner search result
* Change exit owner to Owner after exit 
* Fix sort by values for repeating fields
Jira: https://collectionspace.atlassian.net/browse/DRYD-1618
This was noticed as part of the regression testing that the new `Object Exit` was not pulling back the `Exit Owner` and when trying to sort we saw an `ERR_API`. This turned out to be two separate issues - the first is that the response used `owner` as the field returned for search results. The fix for this is just to align the field name defined in `columns.js` for the object exit with the search result.
The second issue was caused by the `sortBy` field being incorrect for repeating fields. It only needs to specify the top level field and …
> Update search columns for NAGPRA procedures

- docs/configuration/messages.js
- src/plugins/recordTypes/uoc/fields.js
Fixes DRYD-1269
So Kristina can remove stupid extra code from cspace-config-untangler, and so things will be slightly more consistent.
https://collectionspace.atlassian.net/browse/DRYD-1269
I don't see any automated tests for field IDs. 
The UI config should output the new field ids on this field when this is fixed. 
Don't think so
If we think anyone has done significant work on translating/customizing CollectionSpace depending on the changed field ID, might be considered breaking.
The docs/configuration/messages.js file is …
> DRYD-1269: Make field id value match field name

- docs/configuration/messages.js
- src/plugins/recordTypes/collectionobject/fields.js
Fixes DRYD-1270
So Kristina can remove stupid extra code from cspace-config-untangler, and so things will be slightly more consistent.
https://collectionspace.atlassian.net/browse/DRYD-1270
I don't see any automated tests for field IDs. 
The UI config should output the new field ids on this field when this is fixed. 
Don't think so
If we think anyone has done significant work on translating/customizing CollectionSpace depending on the changed field ID, might be considered breaking.
The docs/configuration/messages.js file is …
> DRYD-1270 Fix compressionStandard field id

- docs/configuration/messages.js
- src/plugins/recordTypes/conservation/fields.js
Fixes DRYD-1271
So Kristina can remove stupid extra code from cspace-config-untangler, and so things will be slightly more consistent.
https://collectionspace.atlassian.net/browse/DRYD-1271
I don't see any automated tests for field IDs. 
The UI config should output the new field ids on this field when this is fixed. 
Don't think so
If we think anyone has done significant work on translating/customizing CollectionSpace depending on the changed field ID, might be considered breaking. 
The docs/configuration/messages.js file is …
> DRYD-1271 Change 'nadme' to 'name' in field message id string

- src/plugins/recordTypes/deaccession/serviceConfig.js
- src/plugins/recordTypes/dutyofcare/serviceConfig.js
Makes serviceConfig documentName property downcased for Duty of Care and Deaccession procedures
Other documentName properties are downcased. We don't need MORE inconsistency in CollectionSpace. 
Not sure. Discussed with @mikejritter that this property doesn't really appear to be used for anything, but defer to him how to verify.
??
n/a - [The documentation on this](https://github.com/collectionspace/cspace-ui.js/blob/master/docs/configuration/RecordServiceConfiguration.md) is not really informative
**Did someone actually run this …
> Downcase documentName serviceConfig for Duty of Care, Deaccession

- src/actions/tags.js
* Remove the promise rejection when the servicegroup call fails with a 403
Jira: https://collectionspace.atlassian.net/browse/DRYD-1688
When the response fails and the promise is rejected, this causes the entire login task chain to fail. This results in a blank screen being shown instead of any useful error, because nothing is being propagated back to the user correctly.
* Start collectionspace and run the devserver
* Login as the admin user and create a new user
* Don't assign any roles, just give an email and password
* Logout
* Try to sign in as the new user and get greeted with a ui (although non-functional as you have no roles)
**Dependencies for …
> DRYD-1688: Login Error When No Roles

- test/specs/actions/tags.spec.js
Fixes test failure for DRYD-1688
Jira: https://collectionspace.atlassian.net/browse/DRYD-1688
The logic for the tag action was updated to not reject the promise when a 403 is returned. This updates a test which returned a 403 to no longer expect a rejected promise.
* Run `npm test`
None
No
@mikejritter tested locally
> DRYD-1688: Fix failing test

- src/plugins/recordTypes/collectionobject/fields.js
Fixes a typo in the message id
No jira
This typo impacts the ability to override this message because it doesn't properly reflect what procedure it's a part of.
n/a
None
No
No
> Fix typo in label id

- src/plugins/recordTypes/nagprainventory/fields.js
- src/plugins/recordTypes/summarydocumentation/fields.js
* Updates labels to include 'documentation'
Jira: https://collectionspace.atlassian.net/browse/DRYD-1703 + https://collectionspace.atlassian.net/browse/DRYD-1704
The labels need “Documentation to represent that they are documentation statuses vs workflow statuses.
* Run the dev server, e.g. `npm run devserver --back-end=https://core.dev.collectionspace.org`
* In the NAGPRA Inventory form, verify that the label reads 'Inventory documentation status'
* In the NAGPRA Inventory advanced search, verify that the fields are labeled 'Inventory documentation status ...'
* In the Summary Documentation form, verify that the label reads 'Summary documentation …
> Add documentation to status group labels

- src/plugins/recordTypes/exit/fields.js
- src/plugins/recordTypes/exit/forms/default.jsx
- src/plugins/recordTypes/heldintrust/fields.js
- src/plugins/recordTypes/heldintrust/forms/default.jsx
- src/plugins/recordTypes/nagprainventory/fields.js
- src/plugins/recordTypes/nagprainventory/forms/default.jsx
- src/plugins/recordTypes/summarydocumentation/fields.js
- src/plugins/recordTypes/summarydocumentation/forms/default.jsx
* Adds a `note` field to the following procedures
* Object Exit
* Held-in-Trust
* NAGPRA Inventory
* Summary Documentation
Jira: https://collectionspace.atlassian.net/browse/DRYD-1797
These procedures were added in CollectionSpace 8.1 and needed a general purpose note field to help facilitate data migrations.
* Run the devserver, e.g. `npm run devserver --back-end=https://core.dev.collectionspace.org`
* For each record, verify that the `Note` field exists for each template and can be saved
None
No. The messages will need to be …
> DRYD-1797: Add note to 8.1 procedures

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/collectionobject/forms/timebased.jsx
This adds a repeatable free text `Object production agent` field to the collection object record.
Jira: https://collectionspace.atlassian.net/browse/DRYD-1770
This is intended to complement the authority controlled field to help assist with migration work.
* Create a CollectionObject
* In the `Object Production Information` panel, see that the new field exists
There are two additional templates which have the production panel but it is still being determined if the field should be added to them.
**Has the application documentation been updated for these …
> DRYD-1770: Add production agent verbatim

- src/components/admin/VocabularyUsedByPanel.jsx
- src/helpers/configHelpers.js
- test/specs/components/admin/VocabularyUsedByPanel.spec.jsx
This updates the `findVocabularyUses` to accept a vocabulary type in order to search on specific views.
Jira: https://collectionspace.atlassian.net/browse/DRYD-1732
When looking at terms, the used by panel will search for uses based on the id of the term list being used. In this case, both the term list and id generator share `nagprainventory`, which is causing the ID Generator to show up in the used by panel for the term list. This update changes this to use `TermPickerInput` as the view type when in the `VocabularyUsedBy` component. 
* Run the devserver, e.g. `npm run devserver --back-end=https://core.dev.collectionspace.org`
* Navigate to the Tools > …
> DRYD-1732: Filter Vocabulary Used on TermPickerInput

- src/helpers/validationHelpers.js
- src/plugins/recordTypes/authrole/fields.js
* Adds validation for input length for role description
* Adds validation for input length for role display name
Jira: https://collectionspace.atlassian.net/browse/DRYD-1776
Previously there were no validation errors that would show up, and the response from the api was not readable. This prevents the form from being submitted before all fields are valid, and if there are any errors they are displayed similar to other form errors.
* Run the devserver, e.g. npm run devserver --back-end=https://core.dev.collectionspace.org
* Navigate to Administration > Roles and Permissions
* Try to create a new role with a name which is too long and a description which …
> DRYD-1776: Form validation for role description/role name

- src/components/config/ConfigProvider.jsx
This adds a context for the ConfigProvider. It also adds a function, useConfig, which allows for easy use of the config in functional components.
No jira. As I've been prototyping the new search this is something that has been needed. It's also a bit of a stop gap because of how many components use the contextTypes to get the config.
* run `npm run test` and ensure all test pass
n/a
n/a
@mikejritter tested using core.dev as a backend.
> Add context to ConfigProvider

- src/actions/search.js
- src/plugins/listTypes/index.js
- src/plugins/listTypes/search.js
- src/plugins/recordTypes/collectionobject/serviceConfig.js
* Adds a feature flag to the CollectionObject service config for use with the new search api
* Adds a new list type to match the new api response
* Update search redux action to work with the new search api
Jira: https://collectionspace.atlassian.net/browse/DRYD-1832
This is preliminary work which is being done to allow components to make use of the new API and make use of updated views.
Testing will be ongoing while the new search interface is being developed.
This still needs tests but there's a desire to do testing of the new search prototype on dev so they may be skipped for now.
**Has the …
> DRYD-1382: Add Support For New Search API

- .github/workflows/ci-js.yml
Updates the CI rules to add develop as a branch.
No jira. This allows CI to be run when we create PRs.
* Create a PR
* See CI is run
none
no
no
> Run CI For PRs Against dev

- src/components/pages/search/SearchResults.jsx
- src/components/search/table/SearchResultTableHeader.jsx
- src/components/search/table/SearchTable.jsx
* Adds a SearchResultTableHeader component
* Allows for table headers to be clicked, updating the sort by/order
Jira: https://collectionspace.atlassian.net/browse/DRYD-1804
This is additional work to bring the new SearchResultTable up to feature parity with the existing implementation.
* Search on 'Objects'
* Click the table headers to sort
When changing sort order, the table can be seen resizing. We should have that sorted out before it is released for production.
No
**Did someone actually run this code to …
> DRYD-1804: Sorting for SearchResultTable 

- src/components/pages/search/SearchResults.jsx
- src/components/search/SearchResultFooter.jsx
- src/components/search/table/SearchResultTableHeader.jsx
- src/components/search/table/SearchTable.jsx
* Adds pagination handlers to SearchResultFooter
* Move dispatched actions into useEffect
* Add key to tr
Jira: https://collectionspace.atlassian.net/browse/DRYD-1804
These are more updates to support existing functionality. This time it's just for the pagination controls at the bottom of the form. The page control in the header seems redundant and I'm not sure if we will continue to need it, so I've left it out of this PR.
* Run the devserver against core.dev
* Search against 'Objects'
* Use the page controls underneath the table to control page size/page number
The same issues apply to this as do …
> DRYD-1804: Search Table Pagination

- src/components/search/searchResultHelpers.js
- src/components/search/table/SearchResultTableHeader.jsx
- src/components/search/table/SearchResultTableRow.jsx
- src/components/search/table/SearchTable.jsx
- styles/cspace-ui/SearchTable.css
* Add aria-label to checkbox inputs which have no display area for labels
* Add aria-label and role to table row for interactive semantics
* Add focus styling for table headers and rows
* Add functions for getting search result list/items to simplify null handling
Jira: https://collectionspace.atlassian.net/browse/DRYD-1804
This adds back some of the functionality (link on a row) and missing WCAG requirements to the search result table.
You know maybe I'll write tests for this one.
We'll likely want to double check these with a screen reader at some point to make sure navigation of the result pages …
> DRYD-1804: ARIA/WCAG updates for search table

- src/components/search/SearchResultSummary.jsx
- src/components/search/table/SearchResultTableRow.jsx
* Updates the SearchTable to store the search descriptor for use by the SearchResultTraverser
* Adds a default on click handler for the SearchResultSummary
Jira: https://collectionspace.atlassian.net/browse/DRYD-1804
This is more work to bring the new search table up to parity with the existing implementation. This allows traversal of the search results when navigating from the table by passing the search descriptor along. It also adds a default on click function in the event one is not passed to the SearchResultSummary, which allows the search page to be populated with the existing query.
* Run the dev server
* Search for objects with some condition …
> DRYD-1804: Traversal of Search Results and Store Search Ops
