- src/plugins/recordTypes/index.js
- src/plugins/recordTypes/objectexit/advancedSearch.js
- src/plugins/recordTypes/objectexit/columns.js
- src/plugins/recordTypes/objectexit/fields.js
- src/plugins/recordTypes/objectexit/forms/default.jsx
- src/plugins/recordTypes/objectexit/idGenerators.js
- src/plugins/recordTypes/objectexit/index.js
- src/plugins/recordTypes/objectexit/messages.js
- src/plugins/recordTypes/objectexit/optionLists.js
- src/plugins/recordTypes/objectexit/serviceConfig.js
- src/plugins/recordTypes/objectexit/title.js
- test/specs/plugins/recordTypes/objectexit/advancedSearch.spec.js
- test/specs/plugins/recordTypes/objectexit/columns.spec.js
- test/specs/plugins/recordTypes/objectexit/forms/default.spec.js
- test/specs/plugins/recordTypes/objectexit/index.spec.js
- test/specs/plugins/recordTypes/objectexit/messages.spec.js
- test/specs/plugins/recordTypes/objectexit/optionLists.spec.js
- test/specs/plugins/recordTypes/objectexit/serviceConfig.spec.js
- test/specs/plugins/recordTypes/objectexit/title.spec.js
> DRYD-143: Implement object exit record type plugin

- index.html
- package-lock.json
- package.json
- src/plugins/recordTypes/uoc/fields.js
- src/plugins/recordTypes/uoc/forms/default.jsx
- src/plugins/recordTypes/uoc/idGenerators.js
- src/plugins/recordTypes/uoc/index.js
- src/plugins/recordTypes/uoc/serviceConfig.js
https://issues.collectionspace.org/issues/?filter=17570
> Changes to UOC based on Megan's feedback

- package.json
- src/plugins/recordTypes/conditioncheck/optionLists.js
McGill asked for this, and Megan thinks it's a good addition to the default configuration
> Add exhibition to condition check reasons

- src/plugins/recordTypes/index.js
- src/plugins/recordTypes/transport/advancedSearch.js
- src/plugins/recordTypes/transport/columns.js
- src/plugins/recordTypes/transport/fields.js
- src/plugins/recordTypes/transport/forms/default.jsx
- src/plugins/recordTypes/transport/forms/index.js
- src/plugins/recordTypes/transport/idGenerators.js
- src/plugins/recordTypes/transport/index.js
- src/plugins/recordTypes/transport/messages.js
- src/plugins/recordTypes/transport/optionLists.js
- src/plugins/recordTypes/transport/serviceConfig.js
- src/plugins/recordTypes/transport/title.js
- test/specs/plugins/recordTypes/transport/columns.spec.js
- test/specs/plugins/recordTypes/transport/forms/default.spec.js
- test/specs/plugins/recordTypes/transport/index.spec.js
- test/specs/plugins/recordTypes/transport/messages.spec.js
- test/specs/plugins/recordTypes/transport/serviceConfig.spec.js
- test/specs/plugins/recordTypes/transport/title.spec.js
Resolves: https://collectionspace.atlassian.net/browse/DRYD-943
* Adds ui components for transport procedure
Note: I wasn't really sure what to do for the title, so I only used the `transportReferenceNumber`.
> DRYD-943: Add Transport Procedure

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
Resolves: https://collectionspace.atlassian.net/browse/DRYD-913
* Add annotation fields to collectionobject
> DRYD-913: Add annotation extension to core

- src/plugins/recordTypes/transport/fields.js
Update the Arrival point to use `place` instead of `person`
> DRYD-985: Update Arrival Point field

- src/components/record/RecordSidebar.jsx
- src/components/record/RelatedRecordPanel.jsx
- src/plugins/listTypes/audit.js
- src/plugins/listTypes/index.js
- src/plugins/recordTypes/audit/columns.js
- src/plugins/recordTypes/audit/fields.js
- src/plugins/recordTypes/audit/index.js
- src/plugins/recordTypes/audit/messages.js
- src/plugins/recordTypes/audit/serviceConfig.js
- src/plugins/recordTypes/index.js
Implementation for the Audit Trail Sidebar
* Create audit record
* Create audit list type
* Add additional RelatedRecordPanel for audit records
> DRYD-997: Audit Trail Sidebar

- src/components/record/MiniView.jsx
- styles/cspace-ui/MiniView.css
Resolves: https://collectionspace.atlassian.net/browse/DRYD-979 
I'd still like to get a test in to validate the behavior of the title, otherwise this should be good to go.
> DRYD-979: Add name of Authority to Title 

- src/plugins/recordTypes/collectionobject/optionLists.js
- src/plugins/recordTypes/movement/optionLists.js
For UI-only release (i.e. not waiting for 7.1 release)
Ray says: I’ll just pull your PR into the 6.x branch as well, and cut a new 6.x release that doesn’t require a 7.1 server.
> Zd 11492 and 11476 option list values

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/collectionobject/messages.js
Add fields and layout defined in:
* https://collectionspace.atlassian.net/browse/DRYD-1034
* https://collectionspace.atlassian.net/browse/DRYD-1039
* https://collectionspace.atlassian.net/browse/DRYD-1040
* https://collectionspace.atlassian.net/browse/DRYD-1041
> Add TimeBasedMedia fields

- src/plugins/recordTypes/index.js
- src/plugins/recordTypes/iterationreport/advancedSearch.js
- src/plugins/recordTypes/iterationreport/columns.js
- src/plugins/recordTypes/iterationreport/fields.js
- src/plugins/recordTypes/iterationreport/forms/default.jsx
- src/plugins/recordTypes/iterationreport/forms/index.js
- src/plugins/recordTypes/iterationreport/idGenerators.js
- src/plugins/recordTypes/iterationreport/index.js
- src/plugins/recordTypes/iterationreport/messages.js
- src/plugins/recordTypes/iterationreport/optionLists.js
- src/plugins/recordTypes/iterationreport/serviceConfig.js
- src/plugins/recordTypes/iterationreport/title.js
Jira Ticket: https://collectionspace.atlassian.net/browse/DRYD-1036
Create record type for the iterationreport.
As an additional note -- I just realized I didn't add the usual tests for the record type, I'll add them shortly.
> DRYD-1036: Create Iteration Report procedure

- src/plugins/extensions/dimension/optionLists.js
- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/collectionobject/messages.js
- src/plugins/recordTypes/collectionobject/optionLists.js
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1061
* Fix typo in contract address
* Make API URL field repeatable
* Change Credential Location to a text field
* Add chroma subsampling
* Add channel type
* Add technical attributes for av and software sections
* Add screen resolution and intended duration to dimensions
* Add associated uuid to number type
> DRYD-1061: Updates to TimeBasedMedia fields

- src/plugins/recordTypes/iterationreport/fields.js
- src/plugins/recordTypes/iterationreport/forms/default.jsx
- src/plugins/recordTypes/iterationreport/optionLists.js
Jira: https://collectionspace.atlassian.net/browse/DRYD-1064
* Change label of “installer extent” field to “installer time involved”
* Add new iteration action group of fields
* Add new field called “Artist or representative” to Install/Deinstall group
* Update terms in Artist present/represented dropdown
> DRYD-1064: Updates to iteration report

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/media/fields.js
- src/plugins/recordTypes/media/forms/default.jsx
Jira Ticket: https://collectionspace.atlassian.net/browse/DRYD-1035
Also added to collectionobject per Jira Ticket: https://collectionspace.atlassian.net/browse/DRYD-1061
> DRYD-1035: Add checksum fields to media handling and collectionobject

- src/plugins/recordTypes/collectionobject/forms/index.js
- src/plugins/recordTypes/collectionobject/forms/public.jsx
Resolves: https://collectionspace.atlassian.net/browse/DRYD-1026
> DRYD-1026: Public Browser Template

- src/plugins/recordTypes/collectionobject/forms/index.js
- src/plugins/recordTypes/collectionobject/forms/timebased.jsx
Jira: https://collectionspace.atlassian.net/browse/DRYD-1054
> DRYD-1054: Create template for Time Based Media fields

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
- src/plugins/recordTypes/collectionobject/messages.js
Jira: https://collectionspace.atlassian.net/browse/DRYD-1065
> DRYD-1065: Copyright extension for collectionobject

- src/plugins/recordTypes/collectionobject/fields.js
* Update programminglanguage source
> DRYD-1033: Update programming language vocab

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/timebased.jsx
JIRA(s): 
* https://collectionspace.atlassian.net/browse/DRYD-1135
* https://collectionspace.atlassian.net/browse/DRYD-1143
* DRYD-1135: Update programmingLanguage field to avoid conflict with fcart
* DRYD-1143: Add additional context to library and compiler fields
> DRYD-1135: Rename TBM fields

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/timebased.jsx
Jira: https://collectionspace.atlassian.net/browse/DRYD-1171
* Rename objectComponentStatus
> DRYD-1171: Rename objectComponentStatus

- src/plugins/recordTypes/collectionobject/forms/timebased.jsx
Part of: https://collectionspace.atlassian.net/browse/DRYD-1153
* Removes requested fields from TBM template
> DRYD-1153: Modify fields in TBM template

- src/plugins/recordTypes/collectionobject/fields.js
* Rename requiredapplication to interactingapplication
> Update interacting application source

- src/plugins/recordTypes/loanin/fields.js
- src/plugins/recordTypes/loanin/forms/default.jsx
- src/plugins/recordTypes/loanout/fields.js
- src/plugins/recordTypes/loanout/forms/default.jsx
Jira: https://collectionspace.atlassian.net/browse/DRYD-1191 + https://collectionspace.atlassian.net/browse/DRYD-1192
* DRYD-1191: Add creditLine to loanin
* DRYD-1192: Add creditLine to loanout
> Add credit line to loan in and loan out

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
Jira: https://collectionspace.atlassian.net/browse/DRYD-1167
> DRYD-1167: Add controlled material

- src/plugins/recordTypes/collectionobject/fields.js
- src/plugins/recordTypes/collectionobject/forms/default.jsx
Jira: https://collectionspace.atlassian.net/browse/DRYD-1128
* Add controlled object name to collectionobject
> DRYD-1128: Add controlled object name

- src/plugins/recordTypes/concept/vocabularies.js
- src/plugins/recordTypes/nagprainventory/fields.js
- src/plugins/recordTypes/nagprainventory/forms/default.jsx
* Add archculture to concept authority
* Remove ulan/tgn from sources
* Update inventoryGroup source to deaccessionapprovalgroup
* Update inventoryStatus source to nagpradocumentationstatus 
* Relabel fields
Jira: https://collectionspace.atlassian.net/browse/DRYD-1331
* Check that Concept contains `Archaeological Culture`
* Check that the fields in NAGPRA Inventory no longer source from ulan or tgn
* Check that the `cultureGroup/culture` field can source from archculture
None
**Has the application …
> NAGPRA Inventory QA

- .github/workflows/ci-js.yml
Adds main and version branches to the CI config
No jira
This ensures that all tests/linting rules will pass when merging into version branches.
Wait for the CI rules to be picked up and check that they pass.
None
No
No
> Update CI Branch Targets

- package-lock.json
- package.json
Updates the version to 11.0.0-dev
No jira.
This updates the package version for the next dev cycle. This follows what we had been doing before in terms of release/dev cycles.
No changes to test
None
No
@mikejritter built locally
> Update Package Version to 11.0.0-dev

- CHANGELOG.md
- package-lock.json
- package.json
This updates the package version and changelog for the next release, which will be 10.1.0.
No Jira. I'm trying this out as part of the QA/Release workflow to see if it works well.
n/a
Release for the RC still needs to be merged into main, which can be done after this PR.
Yes, this includes updates to the CHANGELOG. Version references in the wiki might nee to be updated. 
n/a
> Release 10.1.0-rc.0

- package-lock.json
- package.json
Updates the package version for the 10.1.0 release
No jira. This is part of the release process.
n/a
n/a
Release notes need to be added once the entire release is finalized.
n/a
> Update package version to 10.1.0

- .nvmrc
- package-lock.json
- package.json
Sets the package version to 10.2.0
Also adds .nvmrc
No jira. This is starts a new dev cycle. Note that normally we do the next major version, but it seems unnecessary to do all the time; that can be handled when creating the RC if it's needed.
n/a
n/a
n/a
n/a
> Bump 10.2.0
